spring:
  datasource:


  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


application:
  security:
    jwt:
      secret: kvKHL5jkO4wrWWzyH+2fEhOnBp/a9nvwDD2XTE8GFmE=
      expiresIn: 600000

